version: '3.6'

services:
  db:
    restart: always
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USER
    ports:
      - 5432:5432
     
  apod_service:
    build: ./
    environment:
      - PG_URL=$PG_URL
    ports:
      - $PORT:8080
    depends_on:
      - db
    env_file:
      ./.env