version: '3.6'

services:
  postgres:
    restart: always
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USERNAME
    ports:
      - 5432:5432
     
  server:
    build: ./
    environment:
      PG_URL: $APP_PG_URL
      STATIC_TOKEN: $APP_STATIC_TOKEN
    ports:
      - $APP_PORT:8080
    restart: on-failure
    depends_on:
      postgres:
        condition: service_started
    env_file:
      ./.env